g_pdc_construct() was used before the definition and there was a mismatch between the function signature and the one implitictly created by gcc
/homes/demiray/workspace/openair4G/trunk/openair2/UTIL/OPT/probe.c:455: error: static declaration of ‘g_pdu_construct’ follows non-static declaration
/homes/demiray/workspace/openair4G/trunk/openair2/UTIL/OPT/probe.c:280: error: previous implicit declaration of ‘g_pdu_construct’ was here